apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterhub-pv
  namespace: jupyterhub
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/jupyterhub-pv
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-172-13-5-171
  claimRef:
    namespace: jupyterhub
    name: hub-db-dir