apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${CLUSTER_NAME}
  region: ${AWS_DEFAULT_REGION}
  version: "${K8S_VERSION}"
  tags: 
    project: spark-on-eks
    version: "${K8S_VERSION}"
    karpenter.sh/discovery: ${CLUSTER_NAME}

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
  - metadata:
      name: efs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      efsCSIController: true  
  podIdentityAssociations:
  - namespace: "${KARPENTER_NAMESPACE}"
    serviceAccountName: karpenter
    roleName: ${CLUSTER_NAME}-karpenter
    permissionPolicyARNs:
    - arn:${AWS_PARTITION}:iam::${AWS_ACCOUNT_ID}:policy/KarpenterControllerPolicy-${CLUSTER_NAME}

iamIdentityMappings:
- arn: "arn:${AWS_PARTITION}:iam::${AWS_ACCOUNT_ID}:role/KarpenterNodeRole-${CLUSTER_NAME}"
  username: system:node:{{EC2PrivateDNSName}}
  groups:
  - system:bootstrappers
  - system:nodes
  ## If you intend to run Windows workloads, the kube-proxy group should be specified.
  # For more information, see https://github.com/aws/karpenter/issues/5099.
  # - eks:kube-proxy-windows

vpc:
  id: "vpc-06e8bc80bc6c171ae"
  subnets:
    public:
      public-one:
        id: "subnet-07505bf7d9126a5da"
      public-two:
        id: "subnet-0529b5cdfee5b7945"

managedNodeGroups:
- name: ng-job
  instanceType: t3.xlarge
  desiredCapacity: 2
  minSize: 1
  maxSize: 3
  volumeType: gp3
  volumeSize: 50
  privateNetworking: true
  iam:
    attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
    - arn:aws:iam::aws:policy/service-role/AmazonEFSCSIDriverPolicy
    withAddonPolicies:
      ebs: true
      efs: true
  subnets:
  - public-one
  - public-two
  ssh: 
    publicKeyName: my-eks
    allow: true
  tags: 
    nodegroup-name: ng-job

addons:
- name: eks-pod-identity-agent